# Streamlit Secrets Configuration
# This file contains placeholders for API keys
# Actual keys should be set in Streamlit Share's secrets management

# OpenAI API Key
OPENAI_API_KEY = "YOUR_OPENAI_API_KEY"

# Hugging Face API Key
HUGGINGFACE_API_KEY = "YOUR_HUGGINGFACE_API_KEY"

# Claude API Key
CLAUDE_API_KEY = "YOUR_CLAUDE_API_KEY"

# Llama API Key
LLAMA_API_KEY = "YOUR_LLAMA_API_KEY"

# OpenRouter API Keys
OPENROUTER_API_KEY = "YOUR_OPENROUTER_API_KEY"
OPENROUTER_API_KEY_2 = "YOUR_OPENROUTER_API_KEY_2"

# Google Gemini API Key
GEMINI_API_KEY = "YOUR_GEMINI_API_KEY"

# Botpress Workspace ID
BOTPRESS_WORKSPACE_ID = "YOUR_BOTPRESS_WORKSPACE_ID"
